neumino/thinky

lib/document.js
Seems to have been broken by the hook refactor in aa748ff4e00101859847c23e4ccfa74b4e60ddbe.
=> Fix purge on models referenced by a hasMany join

lib/type/array.js, lib/type/boolean.js, lib/type/buffer.js, lib/type/date.js, lib/type/index.js, lib/type/number.js, lib/type/object.js, lib/type/point.js, lib/type/string.js, lib/util.js, test/settings.js
Fixes #185.
Added .id() as an alias for string().optional().
Added .optional() as an alias for .options(enforce_missing: false}).
Added .required() as an alias for .options(enforce_missing: true}).
Modified .options() to merge the given options into the existing options to allow you to write something like: ``myProp: type.string().optional().options({enforce_type: "strict"})``
Added some simple tests for mergeOptions().
=> Add .id(), .optional() and .required() as aliases

lib/document.js, lib/errors.js, lib/model.js, lib/schema.js, lib/type/array.js, lib/type/boolean.js, lib/type/buffer.js, lib/type/date.js, lib/type/number.js, lib/type/object.js, lib/type/point.js, lib/type/string.js, lib/util.js, test/document.js, test/model.js, test/schema.js
It would be helpful to have a new error type for validation errors, similar to the ```DocumentNotFound``` error type defined in https://github.com/neumino/thinky/blob/master/lib/errors.js
The use case I am imagining is for HTTP status code responses in a RESTful API. You could more granularly report to the API consumer whether an error was their fault due to submission of bad data which the thinky model rejects (400), a particular document not being found (404 - which the ```DocumentNotFound``` type is already helpful for), or some other failure (500). 
I believe this new error could be thrown instead of the more generic Error type in https://github.com/neumino/thinky/blob/master/lib/schema.js
If you think this makes sense, I would be happy to try my hand at a pull request for this. …
=> New Error Type: ValidationError

lib/schema.js, test/schema.js
A recent Thinky update broke chainable types inside of a nested object array.
Here is an example of a schema that is currently broken:
```javascript
var thinky = require('thinky')();
var Model = thinky.createModel('Model', {
id : String,
objectArray : [{
myAttribute : thinky.type.object()
}]
});
```
That throws:
```
TypeError: Cannot read property 'enforce_missing' of undefined
at parse (/.../thinky/lib/schema.js:218:123)
at /.../thinky/lib/schema.js:228:28
at Object.loopKeys (/.../thinky/lib/util.js:203:16)
at parse (/.../thinky/lib/schema.js:227:12)
at parse (/.../thinky/lib/schema.js:243:21)
at /.../thinky/lib/schema.js:228:28
at Object.loopKeys (/.../thinky/lib/util.js:203:16)
at Object.parse (/.../thinky/lib/schema.js:227:12)
at new Model (/.../thinky/lib/model.js:34:29)
at …
```
=> Fix embeded chainables

lib/query.js, test/query.js
Here are some proposed changes whose purpose it is to improve readability on the rather complex _execute() function in query.js. There were some low hanging fruit in the form of redundant if/else statements and unused variables, however, most of the branch deals with breaking up the function into separate parts.
I'm fairly new to Thinky (and RethinkDB for that matter) so please forgive me if I've made any rookie mistakes.
=> Refactoring and cleanup of Query's _execute() function

documentation/api/model.md
The docs had a missing reference to `this` in the pre-save hook example:
=> fix `this` ref in docs for models pre save hook

lib/model.js, test/model.js
Fixes #275. After looking at the tests it appears that we were expecting what I would consider the "incorrect" behavior. If the current behavior is intentional feel free to close this and the related issue, just note that it's not [currently documented](http://thinky.io/documentation/api/model/#save) one way or the other right now.
=> `Model.save(object)` should resolve with single object

lib/document.js, lib/model.js, lib/query.js, lib/thinky.js
As discussed in #268, moving the table creation code into model.js and making more use of promises would be good for readability and worth the effort. I took a stab at that and went a bit further by eliminating the custom event listener implementations (`onTableCreated` and `onTableReady`) from the file and replaced them with promise based solutions.
I believe model.js should be easier to reason about after these changes. There are more things that could be done (e.g. the `save` and `_parse` functions could use a bit of polishing) but perhaps its best to not do too huge PRs?
A summary of the proposed changes:
* Introduce a `ready()` function which returns a promise that resolves when the Model's table and relations have been successfully created.
* Replace all use of `onTableReady()` and …
=> Model promises

documentation/api/model.md
I believe there is a typo in the docs for the `Model.belongsTo` relation. Please check my logic:
The docs state that: 
> Define a "belongs to" relation between two models. The foreign key is `leftKey` and will be stored in `OtherModel`.
I believe it should say `Model`, not `OtherModel`
```js
var Post = thinky.createModel("Post", { // <---- the main "Model"
id: type.string(),
title: type.string(),
content: type.string(),
authorId: type.string() // <--- foreign/left key in the main "Model"
});
var Author = thinky.createModel("Author", { // <--- the "OtherModel"
id: type.string(),
name: type.string()
});
Post.belongsTo(Author, "author", "authorId", "id")
```
The docs for hasOne() correctly state than belongsTo() stores the foreign key in the model creating the relation.
> If you want to …
=> Fix belongsTo() relation foreign key description

documentation/feeds.md
`doc.getOldValue()` is equal to `null` in this instance. Changing it to just `doc` gives you the correct data that was just deleted.
=> Fix Feeds documentation around deleting of data

lib/query.js, test/query.js, test/util.js
I often find that when I am using Thinky with some sort of functional library in a computational chain, one of two things happens.
I end up with a lot of models looking like this:
```js
var User = thinky.createModel("User", {
id: type.number(),
age: type.number(),
admin: type.boolean().default(false)
});
User.defineStatic('bind', function() {
return this.run.bind(this);
});
```
Or I end up creating some extraneous lines of code:
```js
query = User.find(req.params.id);
boundQuery = query.run.bind(query);
```
It seemed like a useful addition to make thinky play more nicely with functional libraries that handle promises (like Ramda.js for instance).
=> add Query.prototype.bind()

.idea/jsLibraryMappings.xml, lib/document.js, lib/errors.js, lib/query.js, test/document.js, test/query.js
allows to catch duplicate primary keys
```
document.save()
.then(function(r) {
...
})
.catch(Errors.DuplicatePrimaryKey, function () {
...
})
.error(function (err) {
...
});
```
=> added duplicate primary key error

lib/errors.js
You forgot to overwrite the default prototype.constructor property with the new Error classes created.
I also replace the prototype from
```javascript
new Error
```
with
```javascript
Object.create(Error.prototype)
```
Which is a cleaner way to do an inheritance (not affecting 'this' properties from Error to proto chain ).
=> Fix Errors prototype chain

lib/errors.js, package.json, test/document.js
This is the first change based on the discussion in #417, bringing the errors in thinky into a strict hierarchy based on a common `ThinkyError` base.
This also includes the change to provide the `primaryKey` in the `DocumentNotFound` error, as well as bump to use semver for `rethinkdbdash` to alleviate wercker errors.
=> refactor(errors): provide a proper error hierarchy

package.json
In nodejs 4.* it is not recommend to use .nextTick() because it can cause to starvation, 
and the recommend function is setImmediate() 
the older bluebird version used nextTick()
https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4
=> update bluebird version in order to prevent starvation by nextTick

lib/model.js, package.json, test/settings.js
Expose passing options to internal `r.tableCreate` which allows us to do things like set the table durability, replicas, etc.
=> Accept table options when creating a model

lib/model.js
This PR fixes an issue Tables created by adding a `hasAndBelongsToMany` relation do not properly "inherit" the table configuration from the parent model.
For example, when running a production RethinkDB instance, I configure all the models (and therefore the tables) to have 3 replicas. Tables that are created as a result of the `hasAndBelongsToMany` relation always have 1 replica and 1 shard.
=> Fixing hasAndBelongsToMany shard/replica configuration

documentation/schemas.md
Updated the documentation for Schemas as I saw that there were inconsistencies and duplicate code examples
It appears that declaring 
```
var type = thinky.type;
```
is covered in the quickstart and can possibly be removed here instead of having variations that include it while others that do not.
=> Schemas Documentation Updates

documentation/api/model.md
Took me a while to figure this out.
[Referencing test](https://github.com/isaackwan/thinky/blob/master/test/event.js#L66)
Isaac
=> rename event `delete` to `deleted` in documentation

package.json
The validator package has an XSS vulnerability, we're using a very old version.
Instead of making it a possible breaking change for the current version (8.x) I updated to the nearest version where the security vulnerability has been fxied: 3.34.0
You can read more here: https://snyk.io/vuln/npm:validator:20150313
Since this is a security update a quick response would be appreciated.
=> fix(security): updating vulnerable validator package
